from enum import StrEnum


class UserRole(StrEnum):
    CONSUMER = "CONSUMER"
    WORKER = "WORKER"
    ADMIN = "ADMIN"


class AccountStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    DEACTIVATED = "DEACTIVATED"


class EmergencyLevel(StrEnum):
    RELAXED = "RELAXED"
    NEEDED_IN_A_DAY = "NEEDED_IN_A_DAY"
    URGENT = "URGENT"


class JobStatus(StrEnum):
    POSTED = "POSTED"
    APPLICATIONS = "APPLICATIONS"
    ACCEPTED = "ACCEPTED"
    ADVANCE_PAID = "ADVANCE_PAID"
    STARTED = "STARTED"
    COMPLETION_PENDING = "COMPLETION_PENDING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    DISPUTED = "DISPUTED"
    RESOLVED = "RESOLVED"


class ApplicationStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    COUNTER_OFFER = "COUNTER_OFFER"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    EXPIRED = "EXPIRED"


class NegotiationStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class AgreementStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    DISPUTED = "DISPUTED"


class PaymentType(StrEnum):
    ADVANCE = "ADVANCE"
    FINAL = "FINAL"


class PaymentStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    HELD = "HELD"
    DISPUTED = "DISPUTED"


class ComplaintStatus(StrEnum):
    NEW = "NEW"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESPONDED = "RESPONDED"
    RESOLVED = "RESOLVED"


class ComplaintCategory(StrEnum):
    PAYMENT = "PAYMENT"
    JOB_ISSUE = "JOB_ISSUE"
    WORKER_ISSUE = "WORKER_ISSUE"
    CONSUMER_ISSUE = "CONSUMER_ISSUE"
    CANCELLATION = "CANCELLATION"
    TECHNICAL = "TECHNICAL"
    GENERAL = "GENERAL"
    OTHER = "OTHER"


class DisputeStatus(StrEnum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class CancellationStatus(StrEnum):
    REQUESTED = "REQUESTED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class AvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"


class EvidenceType(StrEnum):
    WORKER_COMPLETION = "WORKER_COMPLETION"
    CONSUMER_COMPLETION = "CONSUMER_COMPLETION"


class NotificationType(StrEnum):
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    APPLICATION_ACCEPTED = "APPLICATION_ACCEPTED"
    APPLICATION_REJECTED = "APPLICATION_REJECTED"
    APPLICATION_WITHDRAWN = "APPLICATION_WITHDRAWN"
    COUNTER_OFFER_CREATED = "COUNTER_OFFER_CREATED"
    COUNTER_OFFER_RECEIVED = "COUNTER_OFFER_RECEIVED"
    COUNTER_OFFER_ACCEPTED = "COUNTER_OFFER_ACCEPTED"
    COUNTER_OFFER_REJECTED = "COUNTER_OFFER_REJECTED"
    AGREEMENT_CREATED = "AGREEMENT_CREATED"
    AGREEMENT_ACTIVE = "AGREEMENT_ACTIVE"
    ADVANCE_PAYMENT_COMPLETED = "ADVANCE_PAYMENT_COMPLETED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    COMPLETION_CONFIRMED = "COMPLETION_CONFIRMED"
    JOB_COMPLETED = "JOB_COMPLETED"
    FINAL_PAYMENT_COMPLETED = "FINAL_PAYMENT_COMPLETED"
    REVIEW_AVAILABLE = "REVIEW_AVAILABLE"
    REVIEW_CREATED = "REVIEW_CREATED"
    COMPLAINT_CREATED = "COMPLAINT_CREATED"
    COMPLAINT_RESPONSE = "COMPLAINT_RESPONSE"
    COMPLAINT_STATUS_CHANGED = "COMPLAINT_STATUS_CHANGED"
    DISPUTE_CREATED = "DISPUTE_CREATED"
    DISPUTE_STATUS_CHANGED = "DISPUTE_STATUS_CHANGED"
    DISPUTE_RESOLVED = "DISPUTE_RESOLVED"
    JOB_CREATED = "JOB_CREATED"
    JOB_STATUS_CHANGED = "JOB_STATUS_CHANGED"
    SCHEDULE_UPDATED = "SCHEDULE_UPDATED"
    ACCOUNT_EVENT = "ACCOUNT_EVENT"