"""initial schema

Revision ID: 45badac89889
Revises: 
Create Date: 2026-09-05 17:28:29.508891
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45badac89889'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('role', sa.Enum('CONSUMER', 'WORKER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='account_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('consumer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('worker_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('working_location', sa.String(length=255), nullable=True),
    sa.Column('working_radius_km', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('areas_served', sa.String(length=500), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('working_radius_km IS NULL OR working_radius_km >= 0', name='ck_worker_radius_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('jobs',
    sa.Column('consumer_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('required_worker_count', sa.Integer(), nullable=False),
    sa.Column('minimum_platform_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('emergency_level', sa.Enum('RELAXED', 'NEEDED_IN_A_DAY', 'URGENT', name='emergency_level'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('POSTED', 'APPLICATIONS', 'ACCEPTED', 'ADVANCE_PAID', 'STARTED', 'COMPLETION_PENDING', 'COMPLETED', 'CANCELLED', 'DISPUTED', 'RESOLVED', name='job_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('minimum_platform_cost >= 0', name='ck_jobs_cost_non_negative'),
    sa.CheckConstraint('required_worker_count > 0', name='ck_jobs_worker_count_positive'),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumer_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_category', 'jobs', ['category'], unique=False)
    op.create_index('ix_jobs_consumer_id', 'jobs', ['consumer_id'], unique=False)
    op.create_index('ix_jobs_scheduled_date', 'jobs', ['scheduled_date'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('worker_skills',
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'skill_id', name='uq_worker_skills_worker_skill')
    )
    op.create_index('ix_worker_skills_worker_id', 'worker_skills', ['worker_id'], unique=False)
    op.create_table('agreements',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('agreed_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('agreed_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('worker_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='agreement_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('agreed_price >= 0', name='ck_agreements_price_non_negative'),
    sa.CheckConstraint('worker_count > 0', name='ck_agreements_worker_count_positive'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agreements_job_id', 'agreements', ['job_id'], unique=False)
    op.create_index('ix_agreements_worker_id', 'agreements', ['worker_id'], unique=False)
    op.create_table('applications',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'COUNTER_OFFER', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', name='application_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('proposed_price >= 0', name='ck_applications_price_non_negative'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'worker_id', name='uq_applications_job_worker')
    )
    op.create_index('ix_applications_job_id', 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_worker_id', 'applications', ['worker_id'], unique=False)
    op.create_table('complaints',
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('PAYMENT', 'JOB_ISSUE', 'WORKER_ISSUE', 'CONSUMER_ISSUE', 'CANCELLATION', 'TECHNICAL', 'GENERAL', 'OTHER', name='complaint_category'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'RESPONDED', 'RESOLVED', name='complaint_status'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_complaints_status', 'complaints', ['status'], unique=False)
    op.create_table('completions',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('worker_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_completions_job_id', 'completions', ['job_id'], unique=False)
    op.create_table('disputes',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('raised_by', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'CLOSED', name='dispute_status'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disputes_status', 'disputes', ['status'], unique=False)
    op.create_table('job_images',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('storage_bucket', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_images_job_id', 'job_images', ['job_id'], unique=False)
    op.create_table('job_requirements',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('worker_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_requirements_job_id', 'job_requirements', ['job_id'], unique=False)
    op.create_table('reviews',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewed_user_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'reviewer_id', 'reviewed_user_id', name='uq_reviews_job_reviewer_target')
    )
    op.create_index('ix_reviews_job_id', 'reviews', ['job_id'], unique=False)
    op.create_table('cancellations',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=True),
    sa.Column('cancelled_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'REJECTED', name='cancellation_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cancellations_job_id', 'cancellations', ['job_id'], unique=False)
    op.create_table('completion_evidence',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('completion_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('storage_bucket', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['completion_id'], ['completions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_completion_evidence_job_id', 'completion_evidence', ['job_id'], unique=False)
    op.create_table('dispute_messages',
    sa.Column('dispute_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispute_messages_dispute_id', 'dispute_messages', ['dispute_id'], unique=False)
    op.create_table('negotiations',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('initiated_by', sa.Uuid(), nullable=False),
    sa.Column('proposed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='negotiation_status'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('proposed_amount >= 0', name='ck_negotiations_amount_non_negative'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_negotiations_job_id', 'negotiations', ['job_id'], unique=False)
    op.create_table('payments',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('agreement_id', sa.Uuid(), nullable=True),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('payee_id', sa.Uuid(), nullable=False),
    sa.Column('agreed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('ADVANCE', 'FINAL', name='payment_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'HELD', 'DISPUTED', name='payment_status'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('advance_amount >= 0', name='ck_payments_advance_non_negative'),
    sa.CheckConstraint('agreed_amount >= 0', name='ck_payments_agreed_non_negative'),
    sa.CheckConstraint('final_amount >= 0', name='ck_payments_final_non_negative'),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index('ix_payments_job_id', 'payments', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_job_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_negotiations_job_id', table_name='negotiations')
    op.drop_table('negotiations')
    op.drop_index('ix_dispute_messages_dispute_id', table_name='dispute_messages')
    op.drop_table('dispute_messages')
    op.drop_index('ix_completion_evidence_job_id', table_name='completion_evidence')
    op.drop_table('completion_evidence')
    op.drop_index('ix_cancellations_job_id', table_name='cancellations')
    op.drop_table('cancellations')
    op.drop_index('ix_reviews_job_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_job_requirements_job_id', table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index('ix_job_images_job_id', table_name='job_images')
    op.drop_table('job_images')
    op.drop_index('ix_disputes_status', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_completions_job_id', table_name='completions')
    op.drop_table('completions')
    op.drop_index('ix_complaints_status', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index('ix_applications_worker_id', table_name='applications')
    op.drop_index('ix_applications_job_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_agreements_worker_id', table_name='agreements')
    op.drop_index('ix_agreements_job_id', table_name='agreements')
    op.drop_table('agreements')
    op.drop_index('ix_worker_skills_worker_id', table_name='worker_skills')
    op.drop_table('worker_skills')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_scheduled_date', table_name='jobs')
    op.drop_index('ix_jobs_consumer_id', table_name='jobs')
    op.drop_index('ix_jobs_category', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('worker_profiles')
    op.drop_table('consumer_profiles')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('skills')
    # ### end Alembic commands ###